//
//  PxePlayerError.h
//  PxeReader
//
//  Created by Tomack, Barry on 9/8/14.
//  Copyright (c) 2014 Pearson. All rights reserved.
//

#import <Foundation/Foundation.h>

extern NSString* const PxePlayerErrorDomain;

typedef NS_ENUM(NSInteger, PxePlayerErrorCode)
{
    PxePlayerUnknownError           	= -1,
    PxePlayerGeneralError           	= 0,
    PxePlayerInvalidURL             	= 1,
    PxePlayerContextLoadError       	= 2,
    PxePlayerImproperInput          	= 3,
    PxePlayerXMLParsingError        	= 4,
    PxePlayerAuthenticationFailure  	= 5,
    PxePlayerMalformedURL           	= 6,
    PxePlayerGlossaryNotFound       	= 7,
    PxePlayerSearchNotInitialized   	= 8,
    PxePlayerMissingDocumentPaths   	= 9,
    PxePlayerPageFailed             	= 10,
    PxePlayerPostWrongJSON          	= 11,
    PxePlayerParseError             	= 12,
    PxePlayerNetworkUnreachable     	= 13,
    PxePlayerJSONParseError         	= 14,
    PxePlayerManagedContextError    	= 15,
    PxePlayerPersistantDataError    	= 16,
    PxePlayerFileError              	= 17,
    PxePlayerNavigationError        	= 18,
    PxePlayerOfflineDataError       	= 19,
    PxePlayerEnvironmentError       	= 20,
    PxePlayerPlaylistError          	= 21,
    PxePlayerTOCError               	= 22,
    PxePlayerDataInterfaceError     	= 23,
    PxePlayerNetworkCallFailed      	= 24,
    PxePlayerManifestError          	= 25,
    PxePlayerNoManifestFoundInStore    	= 26,
    PxePlayerNoDownloadContextProvided 	= 27,
    PxePlayerAnnotationsError           = 28,
    PxePlayerDataMigrationError         = 29,
    PxePlayerMissingAnnotationError     = 30,
    PxePlayerMissingAnnotationIdError   = 31
};

/*!
 All errors generated by the PxePlayer SDK will have an error domain of
 com.pxeplayer.sdk
 */
@interface PxePlayerError : NSObject

+ (NSError *) errorForCode:(PxePlayerErrorCode)errorCode;

+ (NSError *) errorForCode:(PxePlayerErrorCode)errorCode
           localizedString:(NSString*)localizedString;

+ (NSError *) errorForCode:(NSInteger)errorCode
               errorDetail:(NSDictionary*)errorDetail;

+ (NSDictionary *) getLocalizedStrings;

+ (NSString *)getLocalizedStringForErrorCode:(PxePlayerErrorCode)errorCode;

@end
