.TH "PxePlayerDeleteAnnotation" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerDeleteAnnotation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerDeleteAnnotation\&.h>\fP
.PP
Inherits NSObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBcontextId\fP"
.br
.ti -1c
.RI "NSString * \fBidentityId\fP"
.br
.ti -1c
.RI "NSString * \fBcontentId\fP"
.br
.ti -1c
.RI "NSString * \fBannotationDttm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the delete annotation 
.PP
Definition at line 14 of file PxePlayerDeleteAnnotation\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) annotationDttm\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the annotation description 
.PP
Definition at line 34 of file PxePlayerDeleteAnnotation\&.h\&.
.SS "- (NSString*) contentId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the content id 
.PP
Definition at line 29 of file PxePlayerDeleteAnnotation\&.h\&.
.SS "- (NSString*) contextId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the context id 
.PP
Definition at line 19 of file PxePlayerDeleteAnnotation\&.h\&.
.SS "- (NSString*) identityId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the identity id 
.PP
Definition at line 24 of file PxePlayerDeleteAnnotation\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
