.TH "parser/PxePlayerNCXParser.m" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parser/PxePlayerNCXParser.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PxePlayerNCXParser\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "NSString *const \fBkXMLReaderTextNodeKey\fP = @'title'"
.br
.ti -1c
.RI "NSString *const \fBkXMLReaderAttributePrefix\fP = @'@'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "NSString* const kXMLReaderAttributePrefix = @'@'"

.PP
Definition at line 12 of file PxePlayerNCXParser\&.m\&.
.SS "NSString* const kXMLReaderTextNodeKey = @'title'"

.PP
Definition at line 11 of file PxePlayerNCXParser\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
