.TH "PxePlayerSearchPage" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerSearchPage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerSearchPage\&.h>\fP
.PP
Inherits NSObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBtitle\fP"
.br
.ti -1c
.RI "NSString * \fBpageUrl\fP"
.br
.ti -1c
.RI "NSString * \fBtextSnippet\fP"
.br
.ti -1c
.RI "NSArray * \fBwordHits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the search page data 
.PP
Definition at line 13 of file PxePlayerSearchPage\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) pageUrl\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the page URL 
.PP
Definition at line 23 of file PxePlayerSearchPage\&.h\&.
.SS "- (NSString*) textSnippet\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the text snippet 
.PP
Definition at line 28 of file PxePlayerSearchPage\&.h\&.
.SS "- (NSString*) title\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the title of the page 
.PP
Definition at line 18 of file PxePlayerSearchPage\&.h\&.
.SS "- (NSArray*) wordHits\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSArray variable to hold the word hits 
.PP
Definition at line 33 of file PxePlayerSearchPage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
