.TH "PxePlayerXHTMLCDParser()" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerXHTMLCDParser() \- 
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "NSInteger \fBpageNumber\fP"
.br
.ti -1c
.RI "PxePlayerBookDetails * \fBcurrentBook\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file PxePlayerXHTMLCDParser\&.m\&.
.SH "Property Documentation"
.PP 
.SS "- (PxePlayerBookDetails*) currentBook\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.PP
Definition at line 31 of file PxePlayerXHTMLCDParser\&.m\&.
.SS "- (NSInteger) pageNumber\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 30 of file PxePlayerXHTMLCDParser\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
