.TH "PxePlayerMediaQuery" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerMediaQuery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerMediaQuery\&.h>\fP
.PP
Inherits \fBPxePlayerNavigationsQuery\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBmediaType\fP"
.br
.ti -1c
.RI "NSString * \fBindexId\fP"
.br
.ti -1c
.RI "NSInteger \fBstartIndex\fP"
.br
.ti -1c
.RI "NSInteger \fBtotalResult\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the media query 
.PP
Definition at line 15 of file PxePlayerMediaQuery\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) indexId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the index id 
.PP
Definition at line 25 of file PxePlayerMediaQuery\&.h\&.
.SS "- (NSString*) mediaType\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the media type 
.PP
Definition at line 20 of file PxePlayerMediaQuery\&.h\&.
.SS "- (NSInteger) startIndex\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
A NSInteger variable to hold the start index 
.PP
Definition at line 30 of file PxePlayerMediaQuery\&.h\&.
.SS "- (NSInteger) totalResult\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
A NSInteger variable to hold the total result 
.PP
Definition at line 35 of file PxePlayerMediaQuery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
