.TH "PxePlayerChaptersQuery.h" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerChaptersQuery.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PxePlayerNavigationsQuery\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPxePlayerChaptersQuery\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
