.TH "PxePlayerRestConnector.h" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerRestConnector.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPxePlayerRestConnector\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(^ \fBCompletionHandler\fP )(id receivedObj, NSError *error)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void(^ CompletionHandler)(id receivedObj, NSError *error)"

.PP
Definition at line 10 of file PxePlayerRestConnector\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
