.TH "PxePlayerChapter" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerChapter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerChapter\&.h>\fP
.PP
Inherits NSObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBchapterUUID\fP"
.br
.ti -1c
.RI "NSString * \fBtitle\fP"
.br
.ti -1c
.RI "NSString * \fBfrontMatter\fP"
.br
.ti -1c
.RI "NSString * \fBbackMatter\fP"
.br
.ti -1c
.RI "NSString * \fBpageUUIDS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the book chapter data into the model 
.PP
Definition at line 13 of file PxePlayerChapter\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) backMatter\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the back matter of the chapter 
.PP
Definition at line 33 of file PxePlayerChapter\&.h\&.
.SS "- (NSString*) chapterUUID\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the chapter UUID 
.PP
Definition at line 18 of file PxePlayerChapter\&.h\&.
.SS "- (NSString*) frontMatter\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the front matter of the chapter 
.PP
Definition at line 28 of file PxePlayerChapter\&.h\&.
.SS "- (NSString*) pageUUIDS\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the page UUID's of the chapter 
.PP
Definition at line 38 of file PxePlayerChapter\&.h\&.
.SS "- (NSString*) title\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the title of the chapter 
.PP
Definition at line 23 of file PxePlayerChapter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
