.TH "PxePlayerTocQuery" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerTocQuery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerTocQuery\&.h>\fP
.PP
Inherits \fBPxePlayerNavigationsQuery\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSArray * \fBtocUrl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the table of contents query 
.PP
Definition at line 14 of file PxePlayerTocQuery\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSArray*) tocUrl\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSArray variable to hold the list of table of content urls 
.PP
Definition at line 19 of file PxePlayerTocQuery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
