.TH "PxePlayerAddBookmark" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerAddBookmark \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerAddBookmark\&.h>\fP
.PP
Inherits \fBPxePlayerBookmark\fP\&.
.PP
Inherited by \fBPxePlayerDeleteBookmark\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBuri\fP"
.br
.ti -1c
.RI "NSString * \fBidentityID\fP"
.br
.ti -1c
.RI "NSString * \fBcontextID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class derived from the \fBPxePlayerBookmark\fP to parse the add bookmark query into the model 
.PP
Definition at line 15 of file PxePlayerAddBookmark\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) contextID\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the context id 
.PP
Definition at line 30 of file PxePlayerAddBookmark\&.h\&.
.SS "- (NSString*) identityID\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the identity id 
.PP
Definition at line 25 of file PxePlayerAddBookmark\&.h\&.
.SS "- (NSString*) uri\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable for hold the uri 
.PP
Definition at line 20 of file PxePlayerAddBookmark\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
