.TH "<PxePlayerOperationDelegate>" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<PxePlayerOperationDelegate> \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerPageOperation\&.h>\fP
.PP
Inherits <NSObject>\&.
.PP
Inherited by \fBPxePlayerPageOperations()\fP\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(void) - \fBoperationSuccess:\fP"
.br
.ti -1c
.RI "(void) - \fBoperationFailed:error:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A Protocol which send's the instructions while parsing to the class which implemented it  <NSObject>, extented from \fBNSObject\fP 
.PP
Definition at line 16 of file PxePlayerPageOperation\&.h\&.
.SH "Method Documentation"
.PP 
.SS "- (void) operationFailed: (NSString *)key(NSError *)error"
This method would be called when given operation has been failed 
.PP
\fBParameters:\fP
.RS 4
\fINSString,key\fP to identify the operation in the queue 
.br
\fINSError,returns\fP cause of error 
.RE
.PP

.SS "- (void) operationSuccess: (NSString *)key"
This method would be called when given operation has been successfull executed 
.PP
\fBParameters:\fP
.RS 4
\fINSString,key\fP to identify the operation in the queue 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
