.TH "PxePlayerKit.h" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerKit.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PxePlayerAddAnnotationQuery\&.h'\fP
.br
\fC#import 'PxePlayerAddBookmark\&.h'\fP
.br
\fC#import 'PxePlayerAddNoteQuery\&.h'\fP
.br
\fC#import 'PxePlayerAnnotation\&.h'\fP
.br
\fC#import 'PxePlayerAnnotations\&.h'\fP
.br
\fC#import 'PxePlayerBaseQuery\&.h'\fP
.br
\fC#import 'PxePlayerBook\&.h'\fP
.br
\fC#import 'PxePlayerBookmark\&.h'\fP
.br
\fC#import 'PxePlayerBookmarkQuery\&.h'\fP
.br
\fC#import 'PxePlayerBookmarks\&.h'\fP
.br
\fC#import 'PxePlayerBookQuery\&.h'\fP
.br
\fC#import 'PxePlayerBookShelf\&.h'\fP
.br
\fC#import 'PxePlayerChapter\&.h'\fP
.br
\fC#import 'PxePlayerChapters\&.h'\fP
.br
\fC#import 'PxePlayerChaptersQuery\&.h'\fP
.br
\fC#import 'PxePlayerCheckBookmark\&.h'\fP
.br
\fC#import 'PxePlayerContentAnnotationsQuery\&.h'\fP
.br
\fC#import 'PxePlayerDeleteAnnotation\&.h'\fP
.br
\fC#import 'PxePlayerDeleteBookmark\&.h'\fP
.br
\fC#import 'PxePlayerDeleteBookmarkQuery\&.h'\fP
.br
\fC#import 'PxePlayerEditBookmark\&.h'\fP
.br
\fC#import 'PxePlayerInterface\&.h'\fP
.br
\fC#import 'PxePlayerMedia\&.h'\fP
.br
\fC#import 'PxePlayerMediaQuery\&.h'\fP
.br
\fC#import 'PxePlayerMediaType\&.h'\fP
.br
\fC#import 'PxePlayerNavigationsQuery\&.h'\fP
.br
\fC#import 'PxePlayerNote\&.h'\fP
.br
\fC#import 'PxePlayerNoteDeleteQuery\&.h'\fP
.br
\fC#import 'PxePlayerNotes\&.h'\fP
.br
\fC#import 'PxePlayerNotesQuery\&.h'\fP
.br
\fC#import 'PxePlayerPageOperation\&.h'\fP
.br
\fC#import 'PxePlayerPageOperations\&.h'\fP
.br
\fC#import 'PxePlayerPagesQuery\&.h'\fP
.br
\fC#import 'PxePlayerParser\&.h'\fP
.br
\fC#import 'PxePlayerQueryParser\&.h'\fP
.br
\fC#import 'PxePlayerRestConnector\&.h'\fP
.br
\fC#import 'PxePlayerSearchBookQuery\&.h'\fP
.br
\fC#import 'PxePlayerSearchBooksQuery\&.h'\fP
.br
\fC#import 'PxePlayerSearchNCXQuery\&.h'\fP
.br
\fC#import 'PxePlayerSearchPage\&.h'\fP
.br
\fC#import 'PxePlayerSearchPages\&.h'\fP
.br
\fC#import 'PxePlayerSearchURLsQuery\&.h'\fP
.br
\fC#import 'PxePlayerToc\&.h'\fP
.br
\fC#import 'PxePlayerTocQuery\&.h'\fP
.br
\fC#import 'PxePlayerURLConstants\&.h'\fP
.br
\fC#import 'PxePlayerUser\&.h'\fP
.br
\fC#import 'PxePlayerUserQuery\&.h'\fP
.br
\fC#import 'PxePlayerOldUserQuery\&.h'\fP
.br
\fC#import 'PxePlayerMediaCrumb\&.h'\fP
.br
\fC#import 'Reachability\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
