.TH "PxePlayerDeleteBookmarkQuery" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerDeleteBookmarkQuery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerDeleteBookmarkQuery\&.h>\fP
.PP
Inherits \fBPxePlayerNavigationsQuery\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBcontentID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the delete bookmark query 
.PP
Definition at line 14 of file PxePlayerDeleteBookmarkQuery\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) contentID\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the content id 
.PP
Definition at line 19 of file PxePlayerDeleteBookmarkQuery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
