.TH "PxePlayerUser" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerUser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerUser\&.h>\fP
.PP
Inherits NSObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBuuid\fP"
.br
.ti -1c
.RI "NSString * \fBuserName\fP"
.br
.ti -1c
.RI "NSString * \fBfirstName\fP"
.br
.ti -1c
.RI "NSString * \fBlastName\fP"
.br
.ti -1c
.RI "NSString * \fBemail\fP"
.br
.ti -1c
.RI "NSString * \fBrole\fP"
.br
.ti -1c
.RI "NSString * \fBauthToken\fP"
.br
.ti -1c
.RI "NSString * \fBsessionId\fP"
.br
.ti -1c
.RI "NSNumber * \fBexpiresAfter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class for handling user data downloaded from the server 
.PP
Definition at line 13 of file PxePlayerUser\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) authToken\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the user auth token 
.PP
Definition at line 48 of file PxePlayerUser\&.h\&.
.SS "- (NSString*) email\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the user email 
.PP
Definition at line 38 of file PxePlayerUser\&.h\&.
.SS "- (NSNumber*) expiresAfter\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSNumber variable to hold the expires after time interval 
.PP
Definition at line 58 of file PxePlayerUser\&.h\&.
.SS "- (NSString*) firstName\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the user first name 
.PP
Definition at line 28 of file PxePlayerUser\&.h\&.
.SS "- (NSString*) lastName\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the user last name 
.PP
Definition at line 33 of file PxePlayerUser\&.h\&.
.SS "- (NSString*) role\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the user role 
.PP
Definition at line 43 of file PxePlayerUser\&.h\&.
.SS "- (NSString*) sessionId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the session id 
.PP
Definition at line 53 of file PxePlayerUser\&.h\&.
.SS "- (NSString*) userName\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the user name 
.PP
Definition at line 23 of file PxePlayerUser\&.h\&.
.SS "- (NSString*) uuid\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the user UID 
.PP
Definition at line 18 of file PxePlayerUser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
