.TH "parser/PxePlayerNCXParser.h" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parser/PxePlayerNCXParser.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <Foundation/Foundation\&.h>\fP
.br
\fC#import 'PxePlayerBaseParser\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPxePlayerNCXParser\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef NSUInteger \fBXMLReaderOptions\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBXMLReaderOptionsProcessNamespaces\fP = 1 << 0, \fBXMLReaderOptionsReportNamespacePrefixes\fP = 1 << 1, \fBXMLReaderOptionsResolveExternalEntities\fP = 1 << 2 }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef NSUInteger \fBXMLReaderOptions\fP"

.PP
Definition at line 20 of file PxePlayerNCXParser\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"
An enum for specifies whether the receiver reports the namespace and the qualified name of an element, scopr of namespace declarations and declarations of external entities\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIXMLReaderOptionsProcessNamespaces \fP\fP
.TP
\fB\fIXMLReaderOptionsReportNamespacePrefixes \fP\fP
.TP
\fB\fIXMLReaderOptionsResolveExternalEntities \fP\fP
.PP
Definition at line 15 of file PxePlayerNCXParser\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
