.TH "PxePlayerQueryParser" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerQueryParser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerQueryParser\&.h>\fP
.PP
Inherits NSObject\&.
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(NSDictionary *) + \fBparseUserQuery:\fP"
.br
.ti -1c
.RI "(NSDictionary *) + \fBparseOldUserQuery:\fP"
.br
.ti -1c
.RI "(NSDictionary *) + \fBparseTOCQuery:\fP"
.br
.ti -1c
.RI "(NSDictionary *) + \fBparseChaptersQuery:\fP"
.br
.ti -1c
.RI "(NSDictionary *) + \fBparsePagesQuery:\fP"
.br
.ti -1c
.RI "(NSDictionary *) + \fBparseBookShelfQuery:\fP"
.br
.ti -1c
.RI "(NSDictionary *) + \fBparseNavigationsQuery:\fP"
.br
.ti -1c
.RI "(NSDictionary *) + \fBparseBookmarkQuery:\fP"
.br
.ti -1c
.RI "(NSDictionary *) + \fBparseAddBookmarkQuery:\fP"
.br
.ti -1c
.RI "(NSDictionary *) + \fBparseNotesQuery:\fP"
.br
.ti -1c
.RI "(NSDictionary *) + \fBparseAddAnnotationQuery:\fP"
.br
.ti -1c
.RI "(NSDictionary *) + \fBparseUpdateAnnotationQuery:\fP"
.br
.ti -1c
.RI "(NSDictionary *) + \fBparseSearchBookQuery:\fP"
.br
.ti -1c
.RI "(NSDictionary *) + \fBparseInitSearchNCXQuery:\fP"
.br
.ti -1c
.RI "(NSDictionary *) + \fBparseInitSearchURLsQuery:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file PxePlayerQueryParser\&.h\&.
.SH "Method Documentation"
.PP 
.SS "+ (NSDictionary *) parseAddAnnotationQuery: (\fBPxePlayerAddAnnotationQuery\fP*)query"

.PP
Definition at line 126 of file PxePlayerQueryParser\&.m\&.
.SS "+ (NSDictionary *) parseAddBookmarkQuery: (\fBPxePlayerBookmarkQuery\fP*)query"

.PP
Definition at line 104 of file PxePlayerQueryParser\&.m\&.
.SS "+ (NSDictionary *) parseBookmarkQuery: (\fBPxePlayerNavigationsQuery\fP*)query"

.PP
Definition at line 95 of file PxePlayerQueryParser\&.m\&.
.SS "+ (NSDictionary *) parseBookShelfQuery: (\fBPxePlayerBookQuery\fP*)query"

.PP
Definition at line 77 of file PxePlayerQueryParser\&.m\&.
.SS "+ (NSDictionary *) parseChaptersQuery: (\fBPxePlayerChaptersQuery\fP*)query"

.PP
Definition at line 59 of file PxePlayerQueryParser\&.m\&.
.SS "+ (NSDictionary *) parseInitSearchNCXQuery: (\fBPxePlayerSearchNCXQuery\fP*)query"

.PP
Definition at line 178 of file PxePlayerQueryParser\&.m\&.
.SS "+ (NSDictionary *) parseInitSearchURLsQuery: (\fBPxePlayerSearchURLsQuery\fP*)query"

.PP
Definition at line 188 of file PxePlayerQueryParser\&.m\&.
.SS "+ (NSDictionary *) parseNavigationsQuery: (\fBPxePlayerNavigationsQuery\fP*)query"

.PP
Definition at line 86 of file PxePlayerQueryParser\&.m\&.
.SS "+ (NSDictionary *) parseNotesQuery: (\fBPxePlayerNavigationsQuery\fP*)query"

.PP
Definition at line 117 of file PxePlayerQueryParser\&.m\&.
.SS "+ (NSDictionary *) parseOldUserQuery: (\fBPxePlayerOldUserQuery\fP*)query"

.PP
Definition at line 28 of file PxePlayerQueryParser\&.m\&.
.SS "+ (NSDictionary *) parsePagesQuery: (\fBPxePlayerPagesQuery\fP*)query"

.PP
Definition at line 68 of file PxePlayerQueryParser\&.m\&.
.SS "+ (NSDictionary *) parseSearchBookQuery: (\fBPxePlayerSearchBookQuery\fP*)query"

.PP
Definition at line 169 of file PxePlayerQueryParser\&.m\&.
.SS "+ (NSDictionary *) parseTOCQuery: (\fBPxePlayerTocQuery\fP*)query"

.PP
Definition at line 50 of file PxePlayerQueryParser\&.m\&.
.SS "+ (NSDictionary *) parseUpdateAnnotationQuery: (\fBPxePlayerAddAnnotationQuery\fP*)query"

.PP
Definition at line 147 of file PxePlayerQueryParser\&.m\&.
.SS "+ (NSDictionary *) parseUserQuery: (\fBPxePlayerUserQuery\fP*)query"

.PP
Definition at line 39 of file PxePlayerQueryParser\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
