.TH "PxePlayerURLArrayParser" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerURLArrayParser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerURLArrayParser\&.h>\fP
.PP
Inherits NSObject, and \fB<PxePlayerBaseParser>\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A simple class derived from the \fBPxePlayerBaseParser\fP to parse content from the server and returns the result as a array or dictionary format 
.PP
Definition at line 15 of file PxePlayerURLArrayParser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
