.TH "PxePlayerXMLParser" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerXMLParser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerXMLParser\&.h>\fP
.PP
Inherits NSObject\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(NSArray *) - \fBparseData:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class for parsing XML content in to the generic data format such as NSArray or NSDictionary 
.PP
Definition at line 14 of file PxePlayerXMLParser\&.h\&.
.SH "Method Documentation"
.PP 
.SS "- (NSArray *) parseData: (NSData*)data"
This method would be called to parse data and returns the parsed result as a dictionary format 
.PP
\fBParameters:\fP
.RS 4
\fINSData,data\fP need to be parsed 
.RE
.PP

.PP
Definition at line 21 of file PxePlayerXMLParser\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
