.TH "PxePlayerAddNoteQuery" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerAddNoteQuery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerAddNoteQuery\&.h>\fP
.PP
Inherits \fBPxePlayerNotesQuery\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSNumber * \fBroleTypeId\fP"
.br
.ti -1c
.RI "NSNumber * \fBnoteStartPos\fP"
.br
.ti -1c
.RI "NSNumber * \fBnoteEndPos\fP"
.br
.ti -1c
.RI "NSString * \fBnote\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class derived from the \fBPxePlayerNotesQuery\fP to parse the add note query into the model 
.PP
Definition at line 15 of file PxePlayerAddNoteQuery\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) note\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the note text 
.PP
Definition at line 35 of file PxePlayerAddNoteQuery\&.h\&.
.SS "- (NSNumber*) noteEndPos\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSNumber variable to hold the note end position 
.PP
Definition at line 30 of file PxePlayerAddNoteQuery\&.h\&.
.SS "- (NSNumber*) noteStartPos\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSNumber variable to hold the note start position 
.PP
Definition at line 25 of file PxePlayerAddNoteQuery\&.h\&.
.SS "- (NSNumber*) roleTypeId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the role type id 
.PP
Definition at line 20 of file PxePlayerAddNoteQuery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
