.TH "PxePlayerPage" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerPage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerPage\&.h>\fP
.PP
Inherits NSObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBpageId\fP"
.br
.ti -1c
.RI "NSString * \fBpageNumber\fP"
.br
.ti -1c
.RI "NSString * \fBtitle\fP"
.br
.ti -1c
.RI "NSString * \fBcontentFile\fP"
.br
.ti -1c
.RI "NSString * \fBbookmarkId\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the page data 
.PP
Definition at line 13 of file PxePlayerPage\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) bookmarkId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the bookmark id 
.PP
Definition at line 38 of file PxePlayerPage\&.h\&.
.SS "- (NSString*) contentFile\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the content file 
.PP
Definition at line 33 of file PxePlayerPage\&.h\&.
.SS "- (NSString*) pageId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the page id 
.PP
Definition at line 18 of file PxePlayerPage\&.h\&.
.SS "- (NSString*) pageNumber\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the page number 
.PP
Definition at line 23 of file PxePlayerPage\&.h\&.
.SS "- (NSString*) title\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the title 
.PP
Definition at line 28 of file PxePlayerPage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
