.TH "PxePlayerToc" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerToc \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerToc\&.h>\fP
.PP
Inherits NSObject, and <NSCoding>\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSArray * \fBtocEntries\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to handle the array of toc entries parsed from the URL or file\&. 
.PP
Definition at line 14 of file PxePlayerToc\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSArray*) tocEntries\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the array of toc entries 
.PP
Definition at line 19 of file PxePlayerToc\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
