.TH "PxePlayerCheckBookmark" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerCheckBookmark \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerCheckBookmark\&.h>\fP
.PP
Inherits NSObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSNumber * \fBisBookmarked\fP"
.br
.ti -1c
.RI "NSString * \fBforPageUrl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the check bookmark 
.PP
Definition at line 14 of file PxePlayerCheckBookmark\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) forPageUrl\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the page URL 
.PP
Definition at line 24 of file PxePlayerCheckBookmark\&.h\&.
.SS "- (NSNumber*) isBookmarked\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSNumber variable to check the page has bookmarked 
.PP
Definition at line 19 of file PxePlayerCheckBookmark\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
