.TH "PxePlayerSearchURLsQuery" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerSearchURLsQuery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerSearchURLsQuery\&.h>\fP
.PP
Inherits \fBPxePlayerSearchBookQuery\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSArray * \fBcontentURLs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the search url query 
.PP
Definition at line 14 of file PxePlayerSearchURLsQuery\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSArray*) contentURLs\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSArray variable to hold the list of content urls 
.PP
Definition at line 19 of file PxePlayerSearchURLsQuery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
