.TH "PxePlayerNavigationsQuery" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerNavigationsQuery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerNavigationsQuery\&.h>\fP
.PP
Inherits \fBPxePlayerBaseQuery\fP\&.
.PP
Inherited by \fBPxePlayerAddAnnotationQuery\fP, \fBPxePlayerBookmarkQuery\fP, \fBPxePlayerChaptersQuery\fP, \fBPxePlayerContentAnnotationsQuery\fP, \fBPxePlayerDeleteBookmarkQuery\fP, \fBPxePlayerMediaQuery\fP, \fBPxePlayerNotesQuery\fP, \fBPxePlayerPagesQuery\fP, and \fBPxePlayerTocQuery\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBbookUUID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the navigation query 
.PP
Definition at line 14 of file PxePlayerNavigationsQuery\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) bookUUID\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the book UUID 
.PP
Definition at line 19 of file PxePlayerNavigationsQuery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
