.TH "PxePlayerBaseQuery" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerBaseQuery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerBaseQuery\&.h>\fP
.PP
Inherits NSObject\&.
.PP
Inherited by \fBPxePlayerBookQuery\fP, \fBPxePlayerNavigationsQuery\fP, and \fBPxePlayerSearchBooksQuery\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBuserUUID\fP"
.br
.ti -1c
.RI "NSString * \fBauthToken\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the query into the model 
.PP
Definition at line 13 of file PxePlayerBaseQuery\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) authToken\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the auth token 
.PP
Definition at line 23 of file PxePlayerBaseQuery\&.h\&.
.SS "- (NSString*) userUUID\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the user UUID 
.PP
Definition at line 18 of file PxePlayerBaseQuery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
