.TH "parser/PxePlayerURLArrayParser.m" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parser/PxePlayerURLArrayParser.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PxePlayerURLArrayParser\&.h'\fP
.br
\fC#import <CoreData/CoreData\&.h>\fP
.br
\fC#import 'PxePlayerDataManager\&.h'\fP
.br
\fC#import 'PxePlayerPageDetails\&.h'\fP
.br
\fC#import 'PxePlayerBookDetails\&.h'\fP
.br
\fC#import 'PxePlayerToc\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBkErrInvalidInput\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define kErrInvalidInput   1"

.PP
Definition at line 17 of file PxePlayerURLArrayParser\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
