.TH "PxePlayerAddAnnotationQuery" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerAddAnnotationQuery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerAddAnnotationQuery\&.h>\fP
.PP
Inherits \fBPxePlayerNavigationsQuery\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBcontentId\fP"
.br
.ti -1c
.RI "NSMutableArray * \fBannotations\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class derived from the \fBPxePlayerNavigationsQuery\fP to parse the query into the model 
.PP
Definition at line 16 of file PxePlayerAddAnnotationQuery\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSMutableArray*) annotations\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSMutableArray variable to hold the list of annotations 
.PP
Definition at line 26 of file PxePlayerAddAnnotationQuery\&.h\&.
.SS "- (NSString*) contentId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the content id 
.PP
Definition at line 21 of file PxePlayerAddAnnotationQuery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
