.TH "PxePlayerBookShelf" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerBookShelf \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerBookShelf\&.h>\fP
.PP
Inherits NSObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSMutableArray * \fBbooks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the book shelf data into the model 
.PP
Definition at line 13 of file PxePlayerBookShelf\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSMutableArray*) books\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSMutableArray variable to hold the list of book model 
.PP
Definition at line 18 of file PxePlayerBookShelf\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
