.TH "PxePlayerSearchBookQuery" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerSearchBookQuery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerSearchBookQuery\&.h>\fP
.PP
Inherits \fBPxePlayerSearchBooksQuery\fP\&.
.PP
Inherited by \fBPxePlayerSearchNCXQuery\fP, and \fBPxePlayerSearchURLsQuery\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBindexId\fP"
.br
.ti -1c
.RI "NSString * \fBbookId\fP"
.br
.ti -1c
.RI "NSString * \fBcontentId\fP"
.br
.ti -1c
.RI "NSInteger \fBpageNumber\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the book search query 
.PP
Definition at line 16 of file PxePlayerSearchBookQuery\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) bookId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the book id 
.PP
Definition at line 26 of file PxePlayerSearchBookQuery\&.h\&.
.SS "- (NSString*) contentId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the content id 
.PP
Definition at line 31 of file PxePlayerSearchBookQuery\&.h\&.
.SS "- (NSString*) indexId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the index id 
.PP
Definition at line 21 of file PxePlayerSearchBookQuery\&.h\&.
.SS "- (NSInteger) pageNumber\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
A NSInteger variable to hold the page number 
.PP
Definition at line 36 of file PxePlayerSearchBookQuery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
