.TH "PxePlayerBookmarks" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerBookmarks \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerBookmarks\&.h>\fP
.PP
Inherits NSObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBcontextId\fP"
.br
.ti -1c
.RI "NSString * \fBidentityId\fP"
.br
.ti -1c
.RI "NSMutableArray * \fBbookmarks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the bookmarks into the list of models 
.PP
Definition at line 13 of file PxePlayerBookmarks\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSMutableArray*) bookmarks\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSMutableArray variable to hold the list of bookmarks model 
.PP
Definition at line 28 of file PxePlayerBookmarks\&.h\&.
.SS "- (NSString*) contextId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the context id 
.PP
Definition at line 18 of file PxePlayerBookmarks\&.h\&.
.SS "- (NSString*) identityId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the identity id 
.PP
Definition at line 23 of file PxePlayerBookmarks\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
