.TH "PxePlayerInterface.m" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerInterface.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PxePlayerInterface\&.h'\fP
.br
\fC#import 'PxePlayerRestConnector\&.h'\fP
.br
\fC#import 'PxePlayerQueryParser\&.h'\fP
.br
\fC#import 'PxePlayerParser\&.h'\fP
.br
\fC#import 'PxePlayerOldUserQuery\&.h'\fP
.br
\fC#import 'PxePlayerUserQuery\&.h'\fP
.br
\fC#import 'PxePlayerUser\&.h'\fP
.br
\fC#import 'PxePlayerTocQuery\&.h'\fP
.br
\fC#import 'PxePlayerToc\&.h'\fP
.br
\fC#import 'PxePlayerURLConstants\&.h'\fP
.br
\fC#import 'PxePlayerBookQuery\&.h'\fP
.br
\fC#import 'PxePlayerBookShelf\&.h'\fP
.br
\fC#import 'PxePlayerChaptersQuery\&.h'\fP
.br
\fC#import 'PxePlayerChapters\&.h'\fP
.br
\fC#import 'PxePlayerBookmarkQuery\&.h'\fP
.br
\fC#import 'PxePlayerBookmark\&.h'\fP
.br
\fC#import 'PxePlayerCheckBookmark\&.h'\fP
.br
\fC#import 'PxePlayerNotes\&.h'\fP
.br
\fC#import 'PxePlayerContentAnnotationsQuery\&.h'\fP
.br
\fC#import 'PxePlayerAnnotations\&.h'\fP
.br
\fC#import 'PxePlayerAddAnnotationQuery\&.h'\fP
.br
\fC#import 'PxePlayerDeleteAnnotation\&.h'\fP
.br
\fC#import 'PxePlayerNoteDeleteQuery\&.h'\fP
.br
\fC#import 'PxePlayerSearchBookQuery\&.h'\fP
.br
\fC#import 'PxePlayerSearchURLsQuery\&.h'\fP
.br
\fC#import 'PxePlayerNavigationsQuery\&.h'\fP
.br
\fC#import 'PxePlayerMediaQuery\&.h'\fP
.br
\fC#import 'PxePlayerPagesQuery\&.h'\fP
.br
\fC#import 'PxePlayerPage\&.h'\fP
.br
\fC#import 'PxePlayer\&.h'\fP
.br
\fC#import 'PxePlayerSearchPages\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "NSString * \fBcmAPIURL\fP = @'http://devcm-lb-919253956\&.us-west-2\&.elb\&.amazonaws\&.com'"
.br
.ti -1c
.RI "NSString * \fBwebAPIURL\fP = @'http://devpxe-lb-1118429994\&.us-west-2\&.elb\&.amazonaws\&.com/'"
.br
.ti -1c
.RI "NSString * \fBpxeServicesURL\fP = @'http://devpxe-lb-1118429994\&.us-west-2\&.elb\&.amazonaws\&.com/'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "NSString* cmAPIURL = @'http://devcm-lb-919253956\&.us-west-2\&.elb\&.amazonaws\&.com'"
An extern variable for CM services api url 
.PP
Definition at line 43 of file PxePlayerInterface\&.m\&.
.SS "NSString* pxeServicesURL = @'http://devpxe-lb-1118429994\&.us-west-2\&.elb\&.amazonaws\&.com/'"
An extern variable for pxe services url 
.PP
Definition at line 45 of file PxePlayerInterface\&.m\&.
.SS "NSString* webAPIURL = @'http://devpxe-lb-1118429994\&.us-west-2\&.elb\&.amazonaws\&.com/'"
An extern variable for web api url 
.PP
Definition at line 44 of file PxePlayerInterface\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
