.TH "parser/PxePlayerXHTMLCDParser.m" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parser/PxePlayerXHTMLCDParser.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PxePlayerXHTMLCDParser\&.h'\fP
.br
\fC#import 'PxePlayerDataManager\&.h'\fP
.br
\fC#import 'PxePlayer\&.h'\fP
.br
\fC#import 'PxePlayerPageDetails\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNCX_PARENT\fP   @'ol'"
.br
.ti -1c
.RI "#define \fBNCX_CHILDREN\fP   @'li'"
.br
.ti -1c
.RI "#define \fBNCX_ANCHOR\fP   @'a'"
.br
.ti -1c
.RI "#define \fBNCX_SRC\fP   @'href'"
.br
.ti -1c
.RI "#define \fBNCX_NAV_TITLE\fP   @'title'"
.br
.ti -1c
.RI "#define \fBNCX_ID\fP   @'ncx_id'"
.br
.ti -1c
.RI "#define \fBNCX_NAV_LABEL\fP   @'navLabel'"
.br
.ti -1c
.RI "#define \fBNCX_NAV_TEXT\fP   @'text'"
.br
.ti -1c
.RI "#define \fBNCX_PLAYORDER\fP   @'playOrder'"
.br
.ti -1c
.RI "#define \fBNCX_TEXT\fP   @'text'"
.br
.ti -1c
.RI "#define \fBNCX_CONTENT\fP   @'content'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NCX_ANCHOR   @'a'"

.PP
Definition at line 16 of file PxePlayerXHTMLCDParser\&.m\&.
.SS "#define NCX_CHILDREN   @'li'"

.PP
Definition at line 15 of file PxePlayerXHTMLCDParser\&.m\&.
.SS "#define NCX_CONTENT   @'content'"

.PP
Definition at line 25 of file PxePlayerXHTMLCDParser\&.m\&.
.SS "#define NCX_ID   @'ncx_id'"

.PP
Definition at line 20 of file PxePlayerXHTMLCDParser\&.m\&.
.SS "#define NCX_NAV_LABEL   @'navLabel'"

.PP
Definition at line 21 of file PxePlayerXHTMLCDParser\&.m\&.
.SS "#define NCX_NAV_TEXT   @'text'"

.PP
Definition at line 22 of file PxePlayerXHTMLCDParser\&.m\&.
.SS "#define NCX_NAV_TITLE   @'title'"

.PP
Definition at line 18 of file PxePlayerXHTMLCDParser\&.m\&.
.SS "#define NCX_PARENT   @'ol'"

.PP
Definition at line 14 of file PxePlayerXHTMLCDParser\&.m\&.
.SS "#define NCX_PLAYORDER   @'playOrder'"

.PP
Definition at line 23 of file PxePlayerXHTMLCDParser\&.m\&.
.SS "#define NCX_SRC   @'href'"

.PP
Definition at line 17 of file PxePlayerXHTMLCDParser\&.m\&.
.SS "#define NCX_TEXT   @'text'"

.PP
Definition at line 24 of file PxePlayerXHTMLCDParser\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
