.TH "PxePlayerMediaCrumb" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerMediaCrumb \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerMediaCrumb\&.h>\fP
.PP
Inherits NSObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBcrumbId\fP"
.br
.ti -1c
.RI "NSString * \fBtitle\fP"
.br
.ti -1c
.RI "NSString * \fBpageUrl\fP"
.br
.ti -1c
.RI "NSString * \fBpageId\fP"
.br
.ti -1c
.RI "NSString * \fBpageTitle\fP"
.br
.ti -1c
.RI "NSString * \fBchapterId\fP"
.br
.ti -1c
.RI "BOOL \fBdisplay\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the media crumb data 
.PP
Definition at line 13 of file PxePlayerMediaCrumb\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) chapterId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the chapter id 
.PP
Definition at line 43 of file PxePlayerMediaCrumb\&.h\&.
.SS "- (NSString*) crumbId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the crumb id 
.PP
Definition at line 18 of file PxePlayerMediaCrumb\&.h\&.
.SS "- (BOOL) display\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
A BOOL variable to check the bread crumb should be rendered or not 
.PP
Definition at line 48 of file PxePlayerMediaCrumb\&.h\&.
.SS "- (NSString*) pageId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the page id 
.PP
Definition at line 33 of file PxePlayerMediaCrumb\&.h\&.
.SS "- (NSString*) pageTitle\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the page title 
.PP
Definition at line 38 of file PxePlayerMediaCrumb\&.h\&.
.SS "- (NSString*) pageUrl\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the page URL 
.PP
Definition at line 28 of file PxePlayerMediaCrumb\&.h\&.
.SS "- (NSString*) title\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the title 
.PP
Definition at line 23 of file PxePlayerMediaCrumb\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
