.TH "parser/PxePlayerNCXCDParser.m" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parser/PxePlayerNCXCDParser.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PxePlayerNCXCDParser\&.h'\fP
.br
\fC#import 'PxePlayer\&.h'\fP
.br
\fC#import 'PxePlayerPageDetails\&.h'\fP
.br
\fC#import 'PxePlayerDataManager\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNCX_NAVMAP\fP   @'navMap'"
.br
.ti -1c
.RI "#define \fBNCX_NAVPOINT\fP   @'navPoint'"
.br
.ti -1c
.RI "#define \fBNCX_ID\fP   @'id'"
.br
.ti -1c
.RI "#define \fBNCX_NAV_LABEL\fP   @'navLabel'"
.br
.ti -1c
.RI "#define \fBNCX_NAV_TEXT\fP   @'text'"
.br
.ti -1c
.RI "#define \fBNCX_NAV_TITLE\fP   @'title'"
.br
.ti -1c
.RI "#define \fBNCX_PLAYORDER\fP   @'playOrder'"
.br
.ti -1c
.RI "#define \fBNCX_TEXT\fP   @'text'"
.br
.ti -1c
.RI "#define \fBNCX_CONTENT\fP   @'content'"
.br
.ti -1c
.RI "#define \fBNCX_SRC\fP   @'src'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NCX_CONTENT   @'content'"

.PP
Definition at line 22 of file PxePlayerNCXCDParser\&.m\&.
.SS "#define NCX_ID   @'id'"

.PP
Definition at line 16 of file PxePlayerNCXCDParser\&.m\&.
.SS "#define NCX_NAV_LABEL   @'navLabel'"

.PP
Definition at line 17 of file PxePlayerNCXCDParser\&.m\&.
.SS "#define NCX_NAV_TEXT   @'text'"

.PP
Definition at line 18 of file PxePlayerNCXCDParser\&.m\&.
.SS "#define NCX_NAV_TITLE   @'title'"

.PP
Definition at line 19 of file PxePlayerNCXCDParser\&.m\&.
.SS "#define NCX_NAVMAP   @'navMap'"

.PP
Definition at line 14 of file PxePlayerNCXCDParser\&.m\&.
.SS "#define NCX_NAVPOINT   @'navPoint'"

.PP
Definition at line 15 of file PxePlayerNCXCDParser\&.m\&.
.SS "#define NCX_PLAYORDER   @'playOrder'"

.PP
Definition at line 20 of file PxePlayerNCXCDParser\&.m\&.
.SS "#define NCX_SRC   @'src'"

.PP
Definition at line 23 of file PxePlayerNCXCDParser\&.m\&.
.SS "#define NCX_TEXT   @'text'"

.PP
Definition at line 21 of file PxePlayerNCXCDParser\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
