.TH "PxePlayerSearchNCXQuery" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerSearchNCXQuery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerSearchNCXQuery\&.h>\fP
.PP
Inherits \fBPxePlayerSearchBookQuery\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "BOOL \fBindexContent\fP"
.br
.ti -1c
.RI "NSArray * \fBurls\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the search ncx data query 
.PP
Definition at line 14 of file PxePlayerSearchNCXQuery\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (BOOL) indexContent\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
A BOOL variable to check the index content 
.PP
Definition at line 19 of file PxePlayerSearchNCXQuery\&.h\&.
.SS "- (NSArray*) urls\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSArray variable to hold the list of urls 
.PP
Definition at line 24 of file PxePlayerSearchNCXQuery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
