.TH "PxePlayerBookQuery" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerBookQuery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerBookQuery\&.h>\fP
.PP
Inherits \fBPxePlayerBaseQuery\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSNumber * \fBscenarioID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the book query into the model 
.PP
Definition at line 15 of file PxePlayerBookQuery\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSNumber*) scenarioID\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSNumber variable to hold the scenario id 
.PP
Definition at line 20 of file PxePlayerBookQuery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
