.TH "PxePlayerChaptersQuery" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerChaptersQuery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerChaptersQuery\&.h>\fP
.PP
Inherits \fBPxePlayerNavigationsQuery\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A simple class to parse the chapter query 
.PP
Definition at line 14 of file PxePlayerChaptersQuery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
