.TH "PxePlayerSearchBookQuery.h" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerSearchBookQuery.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PxePlayerSearchBooksQuery\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPxePlayerSearchBookQuery\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
