.TH "PxePlayerNCXParser" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerNCXParser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerNCXParser\&.h>\fP
.PP
Inherits NSObject, and \fB<PxePlayerBaseParser>\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A simple class derived from the \fBPxePlayerBaseParser\fP to parse NCX content and returns the result as a array or dictionary format 
.PP
Definition at line 26 of file PxePlayerNCXParser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
