.TH "PxePlayerDeleteBookmark" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerDeleteBookmark \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerDeleteBookmark\&.h>\fP
.PP
Inherits \fBPxePlayerAddBookmark\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A simple class to parse the delete bookmark 
.PP
Definition at line 15 of file PxePlayerDeleteBookmark\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
