.TH "PxePlayerBookmarkQuery" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerBookmarkQuery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerBookmarkQuery\&.h>\fP
.PP
Inherits \fBPxePlayerNavigationsQuery\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBuri\fP"
.br
.ti -1c
.RI "NSString * \fBbookmarkTitle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the bookmark query into the model 
.PP
Definition at line 15 of file PxePlayerBookmarkQuery\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) bookmarkTitle\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the bookmark title 
.PP
Definition at line 25 of file PxePlayerBookmarkQuery\&.h\&.
.SS "- (NSString*) uri\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the uri 
.PP
Definition at line 20 of file PxePlayerBookmarkQuery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
