.TH "PxePlayerXMLParser()" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerXMLParser() \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits <NSXMLParserDelegate>\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSMutableArray * \fBcollections\fP"
.br
.ti -1c
.RI "NSMutableDictionary * \fBentity\fP"
.br
.ti -1c
.RI "NSMutableString * \fBtextInProgress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file PxePlayerXMLParser\&.m\&.
.SH "Property Documentation"
.PP 
.SS "- (NSMutableArray*) collections\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.PP
Definition at line 13 of file PxePlayerXMLParser\&.m\&.
.SS "- (NSMutableDictionary*) entity\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.PP
Definition at line 14 of file PxePlayerXMLParser\&.m\&.
.SS "- (NSMutableString*) textInProgress\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.PP
Definition at line 15 of file PxePlayerXMLParser\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
