.TH "PxePlayerPageOperations()" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerPageOperations() \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fB<PxePlayerOperationDelegate>\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSOperationQueue * \fBdownloadQueue\fP"
.br
.ti -1c
.RI "NSMutableDictionary * \fBoperations\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file PxePlayerPageOperations\&.m\&.
.SH "Property Documentation"
.PP 
.SS "- (NSOperationQueue*) downloadQueue\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.PP
Definition at line 19 of file PxePlayerPageOperations\&.m\&.
.SS "- (NSMutableDictionary*) operations\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.PP
Definition at line 20 of file PxePlayerPageOperations\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
