.TH "PxePlayerUserQuery.m" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerUserQuery.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PxePlayerUserQuery\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAPPKEY\fP   @'NEXT_TEXT_01'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define APPKEY   @'NEXT_TEXT_01'"

.PP
Definition at line 11 of file PxePlayerUserQuery\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
