.TH "PxePlayerAddAnnotationQuery.m" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerAddAnnotationQuery.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PxePlayerAddAnnotationQuery\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
