.TH "PxePlayerPagesQuery" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerPagesQuery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerPagesQuery\&.h>\fP
.PP
Inherits \fBPxePlayerNavigationsQuery\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBchaptersUUID\fP"
.br
.ti -1c
.RI "NSString * \fBpagesUUID\fP"
.br
.ti -1c
.RI "NSString * \fBpageUrl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the pages query data 
.PP
Definition at line 14 of file PxePlayerPagesQuery\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) chaptersUUID\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the chapters UUID 
.PP
Definition at line 19 of file PxePlayerPagesQuery\&.h\&.
.SS "- (NSString*) pagesUUID\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the pages UUID 
.PP
Definition at line 24 of file PxePlayerPagesQuery\&.h\&.
.SS "- (NSString*) pageUrl\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the page URL 
.PP
Definition at line 29 of file PxePlayerPagesQuery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
