.TH "PxePlayerXHTMLCDParser" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerXHTMLCDParser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerXHTMLCDParser\&.h>\fP
.PP
Inherits \fBPxePlayerTocParser\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A simple class derived from the \fBPxePlayerTocParser\fP for converting the array or dictionary of data content parsed from the XHTML parser into the core data model format and returns the result as a models 
.PP
Definition at line 15 of file PxePlayerXHTMLCDParser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
