.TH "PxePlayerNoteDeleteQuery" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerNoteDeleteQuery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerNoteDeleteQuery\&.h>\fP
.PP
Inherits \fBPxePlayerNotesQuery\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBannotationDttm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the note delete query 
.PP
Definition at line 14 of file PxePlayerNoteDeleteQuery\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) annotationDttm\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the annotation definition 
.PP
Definition at line 19 of file PxePlayerNoteDeleteQuery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
