.TH "PxePlayerMedia" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerMedia \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerMedia\&.h>\fP
.PP
Inherits NSObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBmediaId\fP"
.br
.ti -1c
.RI "NSString * \fBmimeType\fP"
.br
.ti -1c
.RI "NSString * \fBcontentFile\fP"
.br
.ti -1c
.RI "NSString * \fBpageNumber\fP"
.br
.ti -1c
.RI "NSString * \fBpageTitle\fP"
.br
.ti -1c
.RI "NSString * \fBpageURL\fP"
.br
.ti -1c
.RI "NSArray * \fBbreadCrumb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the media data 
.PP
Definition at line 13 of file PxePlayerMedia\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSArray*) breadCrumb\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSArray variable to hold the list of bread crumb data 
.PP
Definition at line 48 of file PxePlayerMedia\&.h\&.
.SS "- (NSString*) contentFile\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the content file 
.PP
Definition at line 28 of file PxePlayerMedia\&.h\&.
.SS "- (NSString*) mediaId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the media id 
.PP
Definition at line 18 of file PxePlayerMedia\&.h\&.
.SS "- (NSString*) mimeType\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the mimde type 
.PP
Definition at line 23 of file PxePlayerMedia\&.h\&.
.SS "- (NSString*) pageNumber\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the page number 
.PP
Definition at line 33 of file PxePlayerMedia\&.h\&.
.SS "- (NSString*) pageTitle\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the page title 
.PP
Definition at line 38 of file PxePlayerMedia\&.h\&.
.SS "- (NSString*) pageURL\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the page URL 
.PP
Definition at line 43 of file PxePlayerMedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
