.TH "PxePlayerSearchPages" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerSearchPages \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerSearchPages\&.h>\fP
.PP
Inherits NSObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSInteger \fBtotalPages\fP"
.br
.ti -1c
.RI "NSInteger \fBtotalResults\fP"
.br
.ti -1c
.RI "NSMutableArray * \fBsearchedItems\fP"
.br
.ti -1c
.RI "NSArray * \fBlabels\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to handle the searched pages content 
.PP
Definition at line 13 of file PxePlayerSearchPages\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSArray*) labels\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSArray variable to hold the highlights labels 
.PP
Definition at line 33 of file PxePlayerSearchPages\&.h\&.
.SS "- (NSMutableArray*) searchedItems\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSMutableArray variable to hold the string or model of searched items 
.PP
Definition at line 28 of file PxePlayerSearchPages\&.h\&.
.SS "- (NSInteger) totalPages\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
A NSInteger variable to hold the total pages count per download 
.PP
Definition at line 18 of file PxePlayerSearchPages\&.h\&.
.SS "- (NSInteger) totalResults\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
A NSInteger variable to hold the total results fetched 
.PP
Definition at line 23 of file PxePlayerSearchPages\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
