.TH "PxePlayerEditBookmark" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerEditBookmark \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerEditBookmark\&.h>\fP
.PP
Inherits \fBPxePlayerBookmark\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A simple class to parse the edit bookmark 
.PP
Definition at line 14 of file PxePlayerEditBookmark\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
