.TH "PxePlayerSearchBooksQuery" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerSearchBooksQuery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerSearchBooksQuery\&.h>\fP
.PP
Inherits \fBPxePlayerBaseQuery\fP\&.
.PP
Inherited by \fBPxePlayerSearchBookQuery\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSInteger \fBstartIndex\fP"
.br
.ti -1c
.RI "NSInteger \fBmaxResults\fP"
.br
.ti -1c
.RI "NSString * \fBsearchTerm\fP"
.br
.ti -1c
.RI "NSString * \fBlanguage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the query for search books in bookshelf 
.PP
Definition at line 14 of file PxePlayerSearchBooksQuery\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) language\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the language information 
.PP
Definition at line 34 of file PxePlayerSearchBooksQuery\&.h\&.
.SS "- (NSInteger) maxResults\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
A NSInteger variable to hold the maximum results 
.PP
Definition at line 24 of file PxePlayerSearchBooksQuery\&.h\&.
.SS "- (NSString*) searchTerm\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the search term 
.PP
Definition at line 29 of file PxePlayerSearchBooksQuery\&.h\&.
.SS "- (NSInteger) startIndex\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
A NSInteger variable to hold the start index 
.PP
Definition at line 19 of file PxePlayerSearchBooksQuery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
