.TH "PxePlayerNCXParser()" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerNCXParser() \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits <NSXMLParserDelegate>, and <NSURLConnectionDelegate>\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSMutableArray * \fBdictionaryStack\fP"
.br
.ti -1c
.RI "NSMutableString * \fBtextInProgress\fP"
.br
.ti -1c
.RI "NSError * \fBerrorPointer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file PxePlayerNCXParser\&.m\&.
.SH "Property Documentation"
.PP 
.SS "- (NSMutableArray*) dictionaryStack\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.PP
Definition at line 16 of file PxePlayerNCXParser\&.m\&.
.SS "- (NSError*) errorPointer\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.PP
Definition at line 18 of file PxePlayerNCXParser\&.m\&.
.SS "- (NSMutableString*) textInProgress\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.PP
Definition at line 17 of file PxePlayerNCXParser\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
