.TH "PxePlayerURLArrayParser()" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerURLArrayParser() \- 
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "NSInteger \fBpageNumber\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file PxePlayerURLArrayParser\&.m\&.
.SH "Property Documentation"
.PP 
.SS "- (NSInteger) pageNumber\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 21 of file PxePlayerURLArrayParser\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
