.TH "PxePlayerBookmark" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerBookmark \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerBookmark\&.h>\fP
.PP
Inherits NSObject\&.
.PP
Inherited by \fBPxePlayerAddBookmark\fP, and \fBPxePlayerEditBookmark\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBbookmarkTitle\fP"
.br
.ti -1c
.RI "NSString * \fBuri\fP"
.br
.ti -1c
.RI "NSString * \fBcontentID\fP"
.br
.ti -1c
.RI "NSArray * \fBlabels\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class to parse the bookmark data downloaded from the server into the model 
.PP
Definition at line 12 of file PxePlayerBookmark\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) bookmarkTitle\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the bookmark title 
.PP
Definition at line 17 of file PxePlayerBookmark\&.h\&.
.SS "- (NSString*) contentID\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the content id 
.PP
Definition at line 27 of file PxePlayerBookmark\&.h\&.
.SS "- (NSArray*) labels\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSArray variable to hold the list of labels 
.PP
Definition at line 32 of file PxePlayerBookmark\&.h\&.
.SS "- (NSString*) uri\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the uri 
.PP
Definition at line 22 of file PxePlayerBookmark\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
