.TH "Reachability/Reachability.h" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reachability/Reachability.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <Foundation/Foundation\&.h>\fP
.br
\fC#import <SystemConfiguration/SystemConfiguration\&.h>\fP
.br
\fC#import <netinet/in\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBReachability\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBkReachabilityChangedNotification\fP   @'kNetworkReachabilityChangedNotification'"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBNetworkStatus\fP { \fBNotReachable\fP = 0, \fBReachableViaWiFi\fP, \fBReachableViaWWAN\fP }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define kReachabilityChangedNotification   @'kNetworkReachabilityChangedNotification'"

.PP
Definition at line 59 of file Reachability\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBNetworkStatus\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINotReachable \fP\fP
.TP
\fB\fIReachableViaWiFi \fP\fP
.TP
\fB\fIReachableViaWWAN \fP\fP
.PP
Definition at line 53 of file Reachability\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
