.TH "Reachability/Reachability.m" 3 "Mon Apr 28 2014" "PxeReaderAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reachability/Reachability.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import <sys/socket\&.h>\fP
.br
\fC#import <netinet/in\&.h>\fP
.br
\fC#import <netinet6/in6\&.h>\fP
.br
\fC#import <arpa/inet\&.h>\fP
.br
\fC#import <ifaddrs\&.h>\fP
.br
\fC#import <netdb\&.h>\fP
.br
\fC#import <CoreFoundation/CoreFoundation\&.h>\fP
.br
\fC#import 'Reachability\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBkShouldPrintReachabilityFlags\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define kShouldPrintReachabilityFlags   0"

.PP
Definition at line 59 of file Reachability\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderAPI from the source code\&.
