.TH "NSString(Extension)" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSString(Extension) \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <NSString+Extension\&.h>\fP
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(NSString *) - \fBmd5\fP"
.br
.ti -1c
.RI "(NSComparisonResult) - \fBcompareNumberStrings:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file NSString+Extension\&.h\&.
.SH "Method Documentation"
.PP 
.SS "- (NSComparisonResult) compareNumberStrings: (NSString *)str"

.PP
Definition at line 28 of file NSString+Extension\&.m\&.
.SS "- (NSString *) md5 "

.PP
Definition at line 14 of file NSString+Extension\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
