.TH "NSString+Extension.h" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSString+Extension.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "category \fBNSString(Extension)\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
