.TH "PxePlayerListPage" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerListPage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerListPage\&.h>\fP
.PP
Inherits NSManagedObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSNumber * \fBpageIndex\fP"
.br
.ti -1c
.RI "NSString * \fBpageURL\fP"
.br
.ti -1c
.RI "NSString * \fBurlTag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file PxePlayerListPage\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSNumber*) pageIndex\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"
A NSNumber variable for page index 
.PP
Definition at line 17 of file PxePlayerListPage\&.h\&.
.SS "- (NSString*) pageURL\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"
A NSString variable for page url 
.PP
Definition at line 22 of file PxePlayerListPage\&.h\&.
.SS "- (NSString*) urlTag\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"
A NSString variable for url tag 
.PP
Definition at line 27 of file PxePlayerListPage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
