.TH "PxePlayerPageDetails.m" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerPageDetails.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PxePlayerPageDetails\&.h'\fP
.br
\fC#import 'PxePlayerBookDetails\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
