.TH "PxePlayerLightBoxViewController.m" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerLightBoxViewController.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PxePlayerLightBoxViewController\&.h'\fP
.br
\fC#import 'PxePlayer\&.h'\fP
.br
\fC#import 'PxePlayerRestConnector\&.h'\fP
.br
\fC#import 'HMCache\&.h'\fP
.br
\fC#import 'NSString+Extension\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMEDIA_TYPE\fP   @'type'"
.br
.ti -1c
.RI "#define \fBMEDIA_TYPE_IMAGE\fP   @'image'"
.br
.ti -1c
.RI "#define \fBMEDIA_URL_PATH\fP   @'contentUrl'"
.br
.ti -1c
.RI "#define \fBMEDIA_TITLE\fP   @'title'"
.br
.ti -1c
.RI "#define \fBMEDIA_CAPTION\fP   @'caption'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MEDIA_CAPTION   @'caption'"

.PP
Definition at line 20 of file PxePlayerLightBoxViewController\&.m\&.
.SS "#define MEDIA_TITLE   @'title'"

.PP
Definition at line 19 of file PxePlayerLightBoxViewController\&.m\&.
.SS "#define MEDIA_TYPE   @'type'"

.PP
Definition at line 16 of file PxePlayerLightBoxViewController\&.m\&.
.SS "#define MEDIA_TYPE_IMAGE   @'image'"

.PP
Definition at line 17 of file PxePlayerLightBoxViewController\&.m\&.
.SS "#define MEDIA_URL_PATH   @'contentUrl'"

.PP
Definition at line 18 of file PxePlayerLightBoxViewController\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
