.TH "PxePlayerDataManager()" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerDataManager() \- 
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "NSManagedObjectModel * \fBobjectModel\fP"
.br
.ti -1c
.RI "NSManagedObjectContext * \fBobjectContext\fP"
.br
.ti -1c
.RI "NSPersistentStoreCoordinator * \fBpersistentStoreCoordinator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file PxePlayerDataManager\&.m\&.
.SH "Property Documentation"
.PP 
.SS "- (NSManagedObjectContext*) objectContext\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSManagedObjectContext variable for create context for the current store coordinator 
.PP
Definition at line 27 of file PxePlayerDataManager\&.m\&.
.SS "- (NSManagedObjectModel*) objectModel\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSManagetObjectModel variable for create object model on the particular location for core data persistent store 
.PP
Definition at line 22 of file PxePlayerDataManager\&.m\&.
.SS "- (NSPersistentStoreCoordinator*) persistentStoreCoordinator\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSPersistentStoreCoordinator variable for create store coordinator for the specific location 
.PP
Definition at line 32 of file PxePlayerDataManager\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
