.TH "PxePlayerPageViewController.m" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerPageViewController.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PxePlayerPageViewController\&.h'\fP
.br
\fC#import 'PxePlayerPageContentViewController\&.h'\fP
.br
\fC#import 'PxePlayerPageManager\&.h'\fP
.br
\fC#import 'PxePlayerLoadingView\&.h'\fP
.br
\fC#import 'PxePlayerUIConstants\&.h'\fP
.br
\fC#import 'PxePlayerURLArrayParser\&.h'\fP
.br
\fC#import 'PxePlayerInterface\&.h'\fP
.br
\fC#import 'Reachability\&.h'\fP
.br
\fC#import 'PxePlayer\&.h'\fP
.br
\fC#import 'PxePlayerDataManager\&.h'\fP
.br
\fC#import 'PxePlayerPageDetails\&.h'\fP
.br
\fC#import 'PxePlayerLightBoxViewController\&.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBALERT_TAGS\fP { \fBADD_BOOKMARK_TAG\fP, \fBEDIT_BOOKMARK_TAG\fP, \fBDELETE_BOOKMARK_TAG\fP, \fBBOOKMARK_NO_TITLE_TAG\fP, \fBERROR_TAG\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBALERT_TAGS\fP"
An enumeration of Error and Bookmarks states 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIADD_BOOKMARK_TAG \fP\fP
.TP
\fB\fIEDIT_BOOKMARK_TAG \fP\fP
.TP
\fB\fIDELETE_BOOKMARK_TAG \fP\fP
.TP
\fB\fIBOOKMARK_NO_TITLE_TAG \fP\fP
.TP
\fB\fIERROR_TAG \fP\fP
.PP
Definition at line 27 of file PxePlayerPageViewController\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
