.TH "PxePlayerPageDetails" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerPageDetails \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerPageDetails\&.h>\fP
.PP
Inherits NSManagedObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSNumber * \fBisChildren\fP"
.br
.ti -1c
.RI "NSString * \fBpageId\fP"
.br
.ti -1c
.RI "NSNumber * \fBpageNumber\fP"
.br
.ti -1c
.RI "NSString * \fBpageTitle\fP"
.br
.ti -1c
.RI "NSString * \fBpageURL\fP"
.br
.ti -1c
.RI "NSString * \fBurlTag\fP"
.br
.ti -1c
.RI "NSString * \fBparentId\fP"
.br
.ti -1c
.RI "\fBPxePlayerBookDetails\fP * \fBbook\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file PxePlayerPageDetails\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (\fBPxePlayerBookDetails\fP*) book\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"
A \fBPxePlayerBookDetails\fP variable for book 
.PP
Definition at line 54 of file PxePlayerPageDetails\&.h\&.
.SS "- (NSNumber*) isChildren\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"
A NSNumber boolean variable for to check is children found for toc root 
.PP
Definition at line 19 of file PxePlayerPageDetails\&.h\&.
.SS "- (NSString*) pageId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"
A NSString variable for page id 
.PP
Definition at line 24 of file PxePlayerPageDetails\&.h\&.
.SS "- (NSNumber*) pageNumber\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"
A NSNumber unsigned integer variable for page number 
.PP
Definition at line 29 of file PxePlayerPageDetails\&.h\&.
.SS "- (NSString*) pageTitle\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"
A NSString variable page title 
.PP
Definition at line 34 of file PxePlayerPageDetails\&.h\&.
.SS "- (NSString*) pageURL\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"
A NSString variable for page URL 
.PP
Definition at line 39 of file PxePlayerPageDetails\&.h\&.
.SS "- (NSString*) parentId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"
A NSString variable for parent id 
.PP
Definition at line 49 of file PxePlayerPageDetails\&.h\&.
.SS "- (NSString*) urlTag\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"
A NSString variable for url tag 
.PP
Definition at line 44 of file PxePlayerPageDetails\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
