.TH "PxePlayerDataManager.m" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerDataManager.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PxePlayerDataManager\&.h'\fP
.br
\fC#import 'PxePlayerPageDetails\&.h'\fP
.br
\fC#import 'HMCache\&.h'\fP
.br
\fC#import 'PxePlayerUIConstants\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBkDataModelName\fP   @'PxePlayerDataModel'"
.br
.ti -1c
.RI "#define \fBkDataSqliteName\fP   @'PxePlayerData\&.sqlite'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define kDataModelName   @'PxePlayerDataModel'"

.PP
Definition at line 14 of file PxePlayerDataManager\&.m\&.
.SS "#define kDataSqliteName   @'PxePlayerData\&.sqlite'"

.PP
Definition at line 15 of file PxePlayerDataManager\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
