.TH "PxePlayer()" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayer() \- 
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBPxePlayerDataInterface\fP * \fBdataInterface\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file PxePlayer\&.m\&.
.SH "Property Documentation"
.PP 
.SS "- (\fBPxePlayerDataInterface\fP*) dataInterface\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.PP
Definition at line 51 of file PxePlayer\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
