.TH "PxePlayerPageViewController.h" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerPageViewController.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <UIKit/UIKit\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "protocol \fB<PxePlayerPageViewDelegate>\fP"
.br
.ti -1c
.RI "class \fBPxePlayerPageViewController\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
