.TH "PxePlayerLoadingView.m" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerLoadingView.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PxePlayerLoadingView\&.h'\fP
.br
\fC#import <QuartzCore/QuartzCore\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "CGPathRef \fBNewPathWithRoundRect\fP (CGRect rect, CGFloat cornerRadius)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "CGPathRef NewPathWithRoundRect (CGRectrect, CGFloatcornerRadius)"

.PP
Definition at line 13 of file PxePlayerLoadingView\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
