.TH "PxePlayerAlertView()" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerAlertView() \- 
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "NSMutableDictionary * \fBvalues\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file PxePlayerAlertView\&.m\&.
.SH "Property Documentation"
.PP 
.SS "- (NSMutableDictionary*) values\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.PP
Definition at line 14 of file PxePlayerAlertView\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
