.TH "PxePlayerPagesWebView" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerPagesWebView \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerPagesWebView\&.h>\fP
.PP
Inherits UIWebView\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(id) - \fBinitWithFrame:withScalePageToFit:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class to render a page web view 
.PP
Definition at line 15 of file PxePlayerPagesWebView\&.h\&.
.SH "Method Documentation"
.PP 
.SS "- (id) initWithFrame: (CGRect)frame(BOOL)scalePageToFit"
This method creates the UIWebView instance with custom frame and content auto fit option 
.PP
\fBParameters:\fP
.RS 4
\fICGRect,frame\fP is the custom frame for web view 
.br
\fIBOOL,scalePageToFit\fP is the boolean value to enable/disable auto fit in the UIWebView 
.RE
.PP
\fBReturns:\fP
.RS 4
id, returns the UIWebView instance created with given properties 
.RE
.PP

.PP
Definition at line 18 of file PxePlayerPagesWebView\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
