.TH "PxePlayerDataInterface" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerDataInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerDataInterface\&.h>\fP
.PP
Inherits NSObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBuserName\fP"
.br
.ti -1c
.RI "NSString * \fBcontextId\fP"
.br
.ti -1c
.RI "NSString * \fBuserId\fP"
.br
.ti -1c
.RI "NSString * \fBncxURL\fP"
.br
.ti -1c
.RI "NSString * \fBbaseURL\fP"
.br
.ti -1c
.RI "NSString * \fBauthToken\fP"
.br
.ti -1c
.RI "NSString * \fBsearchIndexId\fP"
.br
.ti -1c
.RI "NSString * \fBafterCrossRefBehaviour\fP"
.br
.ti -1c
.RI "NSString * \fBbookPageTheme\fP"
.br
.ti -1c
.RI "NSInteger \fBbookPageFontSize\fP"
.br
.ti -1c
.RI "NSString * \fBlearningContext\fP"
.br
.ti -1c
.RI "NSArray * \fBmasterPlaylist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file PxePlayerDataInterface\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSString*) afterCrossRefBehaviour\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the after cross reference behaviour 
.PP
Definition at line 51 of file PxePlayerDataInterface\&.h\&.
.SS "- (NSString*) authToken\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the auth token 
.PP
Definition at line 41 of file PxePlayerDataInterface\&.h\&.
.SS "- (NSString*) baseURL\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the base URL 
.PP
Definition at line 36 of file PxePlayerDataInterface\&.h\&.
.SS "- (NSInteger) bookPageFontSize\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
A NSString variable to hold the book page font size 
.PP
Definition at line 61 of file PxePlayerDataInterface\&.h\&.
.SS "- (NSString*) bookPageTheme\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the book page theme 
.PP
Definition at line 56 of file PxePlayerDataInterface\&.h\&.
.SS "- (NSString*) contextId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the context id 
.PP
Definition at line 21 of file PxePlayerDataInterface\&.h\&.
.SS "- (NSString*) learningContext\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the learning context information 
.PP
Definition at line 66 of file PxePlayerDataInterface\&.h\&.
.SS "- (NSArray*) masterPlaylist\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSArray variable to hold the master playlist URL's 
.PP
Definition at line 71 of file PxePlayerDataInterface\&.h\&.
.SS "- (NSString*) ncxURL\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the ncx URL 
.PP
Definition at line 31 of file PxePlayerDataInterface\&.h\&.
.SS "- (NSString*) searchIndexId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the search index id 
.PP
Definition at line 46 of file PxePlayerDataInterface\&.h\&.
.SS "- (NSString*) userId\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the user id 
.PP
Definition at line 26 of file PxePlayerDataInterface\&.h\&.
.SS "- (NSString*) userName\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
A NSString variable to hold the user name 
.PP
Definition at line 16 of file PxePlayerDataInterface\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
