.TH "PxePlayerLightBoxViewController" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerLightBoxViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PxePlayerLightBoxViewController\&.h>\fP
.PP
Inherits UIViewController\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSDictionary * \fBboxInfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Simple class to display image, gadget and external URL's in the lightbox view 
.PP
Definition at line 14 of file PxePlayerLightBoxViewController\&.h\&.
.SH "Property Documentation"
.PP 
.SS "- (NSDictionary*) boxInfo\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
NSDictionary object which holds the necessary object information to render into the screen 
.PP
Definition at line 20 of file PxePlayerLightBoxViewController\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
