.TH "PxePlayerDataInterface.m" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerDataInterface.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PxePlayerDataInterface\&.h'\fP
.br
\fC#import 'PxePlayerUIConstants\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
