.TH "PxePlayerLightBoxViewController()" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerLightBoxViewController() \- 
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "IBOutlet UILabel * \fBinfo\fP"
.br
.ti -1c
.RI "IBOutlet UILabel * \fBcaption\fP"
.br
.ti -1c
.RI "IBOutlet UIImageView * \fBimageView\fP"
.br
.ti -1c
.RI "IBOutlet UIWebView * \fBwView\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file PxePlayerLightBoxViewController\&.m\&.
.SH "Property Documentation"
.PP 
.SS "- (IBOutlet UILabel*) caption\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"
Label to display the title of the image or gadget 
.PP
Definition at line 32 of file PxePlayerLightBoxViewController\&.m\&.
.SS "- (IBOutlet UIImageView*) imageView\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"
UIImageView to display the image in lightbox 
.PP
Definition at line 37 of file PxePlayerLightBoxViewController\&.m\&.
.SS "- (IBOutlet UILabel*) info\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"
Label to display the information about image or gadget 
.PP
Definition at line 27 of file PxePlayerLightBoxViewController\&.m\&.
.SS "- (IBOutlet UIWebView*) wView\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"
UIWebView to load the gadget or external URL's in lightbox view 
.PP
Definition at line 42 of file PxePlayerLightBoxViewController\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
