.TH "PxePlayerUIUtil.m" 3 "Mon Apr 28 2014" "PxeReaderUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxePlayerUIUtil.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PxePlayerUIUtil\&.h'\fP
.br
\fC#import 'PxePlayerUIConstants\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBkDefaultFont\fP   [UIFont systemFontOfSize:12]"
.br
.ti -1c
.RI "#define \fBkDefaultBgColor\fP   [UIColor clearColor]"
.br
.ti -1c
.RI "#define \fBkDefaultTextColor\fP   [UIColor blackColor]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define kDefaultBgColor   [UIColor clearColor]"

.PP
Definition at line 14 of file PxePlayerUIUtil\&.m\&.
.SS "#define kDefaultFont   [UIFont systemFontOfSize:12]"

.PP
Definition at line 13 of file PxePlayerUIUtil\&.m\&.
.SS "#define kDefaultTextColor   [UIColor blackColor]"

.PP
Definition at line 15 of file PxePlayerUIUtil\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PxeReaderUI from the source code\&.
